# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/LCDF-Project-Danmaku-shooting-game/Danmaku-Shooting/Danmaku-Shooting.srcs/sources_1/ip/ROM_f/ROM_f.xci
# IP: The module: 'ROM_f' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/LCDF-Project-Danmaku-shooting-game/Danmaku-Shooting/Danmaku-Shooting.gen/sources_1/ip/ROM_f/ROM_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_f'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: z:/LCDF-Project-Danmaku-shooting-game/Danmaku-Shooting/Danmaku-Shooting.srcs/sources_1/ip/ROM_f/ROM_f.xci
# IP: The module: 'ROM_f' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/LCDF-Project-Danmaku-shooting-game/Danmaku-Shooting/Danmaku-Shooting.gen/sources_1/ip/ROM_f/ROM_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_f'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
